import { useEffect, useState } from 'react';

const RULES = {
  PORT_SCAN: { label: 'Port Scan', fields: [['threshold','Unique ports threshold','20','ports','Distinct destination ports before an alert.'],['window','Detection window','5','seconds','Time used to count ports.'],['cooldown','Alert cooldown','60','seconds','Wait before another alert.']] },
  CONNECTION_BURST: { label: 'Connection Burst', fields: [['threshold','Packet threshold','100','packets','TCP/UDP packets from one source before an alert.'],['window','Detection window','10','seconds','Time used to count packets.'],['cooldown','Alert cooldown','60','seconds','Wait before another alert.']] },
  TRAFFIC_SPIKE: { label: 'Traffic Spike', fields: [['multiplier','Spike multiplier','3','x baseline','Current traffic must exceed this multiple.'],['min_samples','Minimum samples','5','samples','Samples required before a baseline.'],['cooldown','Alert cooldown','30','seconds','Wait before another alert.']] },
  DNS_ANOMALY: { label: 'DNS Anomaly', fields: [['threshold','DNS query threshold','50','queries','Queries from one source before an alert.'],['window','DNS window','10','seconds','Time used to count DNS queries.'],['long_domain_length','Long domain length','50','characters','Longer query creates an alert.'],['cooldown','Alert cooldown','60','seconds','Wait before another alert.']] },
  UNTRUSTED_OUTBOUND: { label: 'Untrusted Outbound', fields: [] },
};

export default function SecurityControls({ rules=[], trusted=[], suppressions=[], activity=[], network={}, captureStatus={}, onRefresh, onSaveNetwork, onSaveRule, onAddTrusted, onDeleteTrusted, onAddSuppression }) {
  const [ruleType,setRuleType]=useState('PORT_SCAN'), [enabled,setEnabled]=useState(true), [values,setValues]=useState({});
  const [mode,setMode]=useState(network.mode||'auto'), [iface,setIface]=useState(network.selected_interface||'');
  const [trustedForm,setTrustedForm]=useState({ip_address:'',description:'',policy:{suppressed_types:[]}}), [suppression,setSuppression]=useState({alert_type:'',source_ip:'',destination_ip:'',reason:'',expires_at:''});
  useEffect(()=>{setMode(network.mode||'auto');setIface(network.selected_interface||'')},[network.mode,network.selected_interface]);
  const selectRule=t=>{const r=rules.find(x=>x.rule_type===t);setRuleType(t);setEnabled(r?.enabled??true);setValues(r?.settings||{})};
  const saveRule=async e=>{e.preventDefault();const settings=Object.fromEntries(Object.entries(values).filter(([,v])=>v!=='').map(([k,v])=>[k,Number(v)]));await onSaveRule(ruleType,{enabled,settings})};
  return <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
    <section className="card"><h2 className="text-lg font-semibold mb-3">Network Capture</h2><form onSubmit={async e=>{e.preventDefault();await onSaveNetwork({mode,interface_name:mode==='manual'?iface:null})}} className="space-y-3"><div className="flex gap-4 text-sm"><label><input type="radio" checked={mode==='auto'} onChange={()=>setMode('auto')}/> Automatic (Recommended)</label><label><input type="radio" checked={mode==='manual'} onChange={()=>setMode('manual')}/> Manual</label></div><label className="text-sm block">Interface<select className="control mt-1" disabled={mode!=='manual'} value={iface} onChange={e=>setIface(e.target.value)}><option value="">{mode==='auto'?`Automatically selected: ${captureStatus.interface||'pending'}`:'Select an available interface'}</option>{(network.interfaces||[]).filter(i=>i.available).map(i=><option key={i.capture_name} value={i.capture_name}>{i.name}{i.ipv4?` - ${i.ipv4}`:''}</option>)}</select></label>{mode==='manual'&&<p className="text-xs text-cyber-400">Only currently available Scapy interfaces can be selected.</p>}<p className="text-sm">Status: <span className={captureStatus.running?'text-cyber-green':'text-red-300'}>{captureStatus.running?'Capturing':'Capture inactive'}</span></p>{captureStatus.last_error&&<p className="text-xs text-red-300">{captureStatus.last_error}</p>}<div className="flex gap-2"><button className="action">Apply capture selection</button><button type="button" className="text-sm text-cyber-accent" onClick={onRefresh}>Refresh interfaces</button></div></form></section>
    <section className="card"><h2 className="text-lg font-semibold mb-3">Detection Rules</h2><form onSubmit={saveRule} className="space-y-3"><select value={ruleType} onChange={e=>selectRule(e.target.value)} className="control">{Object.entries(RULES).map(([k,r])=><option key={k} value={k}>{r.label}</option>)}</select><label className="flex gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enabled</label>{RULES[ruleType].fields.map(([key,label,def,unit,help])=><label key={key} className="block text-sm"><span>{label}</span><div className="flex gap-2 mt-1"><input type="number" min="0" step="any" className="control" value={values[key]??''} placeholder={`e.g. ${def}`} onChange={e=>setValues({...values,[key]:e.target.value})}/><span className="pt-2 text-xs text-cyber-400">{unit}</span></div><span className="text-xs text-cyber-400">{help} Empty uses backend default: {def}.</span></label>)}{!RULES[ruleType].fields.length&&<p className="text-sm text-cyber-400">No numeric runtime settings. Destination lists remain environment configuration.</p>}<button className="action">Save rule</button></form></section>
    <section className="card"><h2 className="text-lg font-semibold mb-3">Trusted Devices</h2><form onSubmit={async e=>{e.preventDefault();await onAddTrusted(trustedForm);setTrustedForm({ip_address:'',description:'',policy:{suppressed_types:[]}})}} className="space-y-2"><div className="flex gap-2"><input required className="control" placeholder="IP address" value={trustedForm.ip_address} onChange={e=>setTrustedForm({...trustedForm,ip_address:e.target.value})}/><input className="control" placeholder="Description" value={trustedForm.description} onChange={e=>setTrustedForm({...trustedForm,description:e.target.value})}/></div><p className="text-xs text-cyber-400">Suppress only expected alert types. Suppressed alerts are retained as evidence but do not create incidents or risk.</p><div className="flex flex-wrap gap-3 text-xs">{['PORT_SCAN','CONNECTION_ANOMALY','TRAFFIC_ANOMALY','DNS_ANOMALY','SUSPICIOUS_OUTBOUND'].map(type=><label key={type}><input type="checkbox" checked={trustedForm.policy.suppressed_types.includes(type)} onChange={e=>setTrustedForm({...trustedForm,policy:{suppressed_types:e.target.checked?[...trustedForm.policy.suppressed_types,type]:trustedForm.policy.suppressed_types.filter(x=>x!==type)}})}/> {type}</label>)}</div><button className="action">Trust device</button></form>{trusted.map(i=><div key={i.id} className="flex justify-between text-sm py-1"><span>{i.ip_address} {i.description} <span className="text-cyber-400">({i.policy?.suppressed_types?.join(', ')||'normal detection'})</span></span><button className="text-red-300" onClick={()=>onDeleteTrusted(i.id)}>Remove</button></div>)}</section>
    <section className="card"><h2 className="text-lg font-semibold mb-3">Alert Suppression</h2><form onSubmit={async e=>{e.preventDefault();await onAddSuppression({...suppression,alert_type:suppression.alert_type||null,source_ip:suppression.source_ip||null,destination_ip:suppression.destination_ip||null,expires_at:suppression.expires_at||null});setSuppression({alert_type:'',source_ip:'',destination_ip:'',reason:'',expires_at:''})}} className="grid grid-cols-2 gap-2"><input className="control" placeholder="Alert type optional" value={suppression.alert_type} onChange={e=>setSuppression({...suppression,alert_type:e.target.value})}/><input className="control" placeholder="Source IP optional" value={suppression.source_ip} onChange={e=>setSuppression({...suppression,source_ip:e.target.value})}/><input required className="control col-span-2" placeholder="Reason" value={suppression.reason} onChange={e=>setSuppression({...suppression,reason:e.target.value})}/><button className="action">Create suppression</button></form>{suppressions.map(i=><div key={i.id} className="text-xs py-1">{i.alert_type||'ANY'} - {i.reason}</div>)}</section>
    <section className="card"><h2 className="text-lg font-semibold mb-3">Live Activity</h2><div className="max-h-64 overflow-auto space-y-2">{activity.length?activity.map(e=><div key={e.id} className="text-sm border-b border-cyber-700/40 pb-1">{e.message}</div>):<p className="text-cyber-400 text-sm">No persisted activity yet.</p>}</div></section>
  </div>;
}
