import { useState } from 'react';
const empty={indicator_type:'IPV4',value:'',source:'local-test',description:'',tags:'lab',confidence:.5,severity:'MEDIUM',expires_at:''};
export default function ThreatIntelligence({ stats={}, indicators=[], matches=[], investigations=[], onCreate, onUpdate, onDisable, onImport, onInvestigate }) {
const [form,setForm]=useState(empty),[search,setSearch]=useState(''),[result,setResult]=useState(null),[ai,setAi]=useState({indicator_type:'IPV4',indicator_value:'',reason:'Manual analyst investigation',language:'en'}),[selected,setSelected]=useState(null),[aiError,setAiError]=useState(''),[investigating,setInvestigating]=useState(false);
 const filtered=indicators.filter(i=>i.value.includes(search.toLowerCase())||i.source.toLowerCase().includes(search.toLowerCase()));
 const save=async e=>{e.preventDefault();try{await onCreate({...form,confidence:Number(form.confidence),expires_at:form.expires_at||null});setForm(empty)}catch(err){alert(err.message)}};
 return <div className="space-y-6"><h2 className="text-2xl font-bold">Threat Intelligence</h2><div className="grid grid-cols-2 md:grid-cols-5 gap-4">{[['Total',stats.total_indicators],['Active',stats.active_indicators],['Disabled',stats.disabled_indicators],['Expired',stats.expired_indicators],['Matches',stats.recent_matches]].map(([n,v])=><div className="stat-card" key={n}><span className="text-2xl font-bold text-cyber-accent">{v??0}</span><span className="stat-label">{n}</span></div>)}</div>
 <div className="grid xl:grid-cols-2 gap-6"><section className="card"><h3 className="text-lg font-semibold mb-3">Add Indicator</h3><form onSubmit={save} className="grid grid-cols-2 gap-2"><select className="control" value={form.indicator_type} onChange={e=>setForm({...form,indicator_type:e.target.value})}>{['IPV4','IPV6','DOMAIN','URL'].map(x=><option key={x}>{x}</option>)}</select><input className="control" required placeholder="Value" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/><input className="control" placeholder="Source" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/><input className="control" type="number" min="0" max="1" step=".05" value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}/><select className="control" value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><input className="control" type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/><input className="control col-span-2" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="action">Create indicator</button></form></section>
 <ImportPanel onImport={onImport} result={result} setResult={setResult}/></div>
 <section className="card"><div className="flex justify-between mb-3"><h3 className="text-lg font-semibold">Indicators</h3><input className="control w-64" placeholder="Search value/source" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Value</th><th>Type</th><th>Source</th><th>Confidence</th><th>Severity</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(i=><tr key={i.id} className="border-t border-cyber-700"><td className="p-2 font-mono">{i.value}</td><td>{i.indicator_type}</td><td>{i.source}</td><td>{Math.round(i.confidence*100)}%</td><td>{i.severity}</td><td>{i.enabled?'ACTIVE':'DISABLED'}</td><td className="space-x-2"><button className="text-cyber-accent" onClick={()=>setAi({...ai,indicator_type:i.indicator_type,indicator_value:i.value})}>Investigate AI</button>{i.enabled&&<button className="text-red-300" onClick={()=>{if(confirm('Disable indicator? Historical matches stay available.'))onDisable(i.id)}}>Disable</button>}</td></tr>)}</tbody></table></div></section>
 <section className="card"><h3 className="text-lg font-semibold mb-1">AI Investigation</h3><p className="mb-3 text-sm text-slate-300">Investigate an indicator with Gemini. AI enriches evidence; it does not change detection or risk.</p><form className="grid grid-cols-1 md:grid-cols-2 gap-3" onSubmit={async e=>{e.preventDefault();setAiError('');setInvestigating(true);try{const r=await onInvestigate(ai);setSelected(r)}catch(err){setAiError(err.message)}finally{setInvestigating(false)}}}><label className="text-sm font-medium text-slate-200">Indicator<input required className="control mt-1" placeholder="IP address, domain, or URL" value={ai.indicator_value} onChange={e=>setAi({...ai,indicator_value:e.target.value})}/></label><label className="text-sm font-medium text-slate-200">Indicator type<select className="control mt-1" value={ai.indicator_type} onChange={e=>setAi({...ai,indicator_type:e.target.value})}>{['IPV4','IPV6','DOMAIN','URL'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium text-slate-200">Investigation Language<select className="control mt-1" value={ai.language} onChange={e=>setAi({...ai,language:e.target.value})}><option value="en">English</option><option value="am">አማርኛ</option></select></label><label className="text-sm font-medium text-slate-200 md:col-span-2">Reason for investigation<input className="control mt-1" placeholder="Why this indicator needs review" value={ai.reason} onChange={e=>setAi({...ai,reason:e.target.value})}/></label><button className="action w-fit" disabled={investigating}>{investigating?'● Investigating…':'Investigate with AI'}</button></form>{investigating&&<p className="ai-status ai-status-running mt-4">● Investigating indicator. Temporary provider failures retry automatically.</p>}{aiError&&<p className="ai-status ai-status-failed mt-4">⚠ AI investigation failed: {aiError}. Local monitoring remains active.</p>}{selected&&<Investigation item={selected} onRetry={()=>onInvestigate(ai).then(setSelected).catch(e=>setAiError(e.message))}/>}</section>
 <section className="card"><h3 className="text-lg font-semibold mb-3">Investigation History</h3>{investigations.length?<div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Indicator</th><th>Type</th><th>Assessment</th><th>AI Confidence</th><th>Status</th><th>Time</th></tr></thead><tbody>{investigations.map(item=><tr key={item.id} className="border-t border-cyber-700 cursor-pointer" onClick={()=>setSelected(item)}><td className="p-2 font-mono">{item.indicator_value}</td><td>{item.indicator_type}</td><td>{item.assessment||'-'}</td><td>{item.confidence==null?'-':`${Math.round(item.confidence*100)}%`}</td><td>{item.status}</td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<p className="text-cyber-400 text-sm">No AI investigations saved yet.</p>}{selected&&<Investigation item={selected}/>}</section>
 <section className="card"><h3 className="text-lg font-semibold mb-3">Recent TI Matches</h3>{matches.length?matches.map(m=><div key={m.id} className="border-b border-cyber-700 py-2 text-sm"><span className="font-mono text-cyber-accent">{m.indicator_value}</span> matched {m.matched_field} — {m.source_ip||'-'} → {m.destination_ip||'-'}</div>):<p className="text-cyber-400">No persisted matches yet.</p>}</section></div>
}
const examples={
 json: JSON.stringify([{indicator_type:'DOMAIN',value:'training-example.invalid',source:'synthetic-training',description:'Safe synthetic domain for import testing',tags:'training,safe',confidence:0.5,severity:'MEDIUM',enabled:true}],null,2),
 csv: 'indicator_type,value,source,description,tags,confidence,severity,enabled\nDOMAIN,training-example.invalid,synthetic-training,Safe synthetic domain for import testing,"training,safe",0.5,MEDIUM,true'
};
function ImportPanel({onImport,result,setResult}) {
 const [format,setFormat]=useState(null),[drafts,setDrafts]=useState({json:'',csv:''}),[error,setError]=useState('');
 const content=format?drafts[format]:'';
 const setContent=value=>setDrafts({...drafts,[format]:value});
 const upload=e=>{const file=e.target.files?.[0];if(!file)return;const next=file.name.toLowerCase().endsWith('.csv')?'csv':'json';const reader=new FileReader();reader.onload=()=>{setDrafts({...drafts,[next]:String(reader.result)});setFormat(next);setError('')};reader.readAsText(file)};
 const submit=async()=>{setError('');setResult(null);if(!content.trim()){setError(`Paste ${format?.toUpperCase()||'import'} data or use the example first.`);return}try{if(format==='json')JSON.parse(content);setResult(await onImport({format,content}))}catch(e){setError(e.message)} };
 if(!format)return <section className="card"><h3 className="text-lg font-semibold">Import Threat Intelligence</h3><p className="mt-1 text-sm text-slate-200">Choose an input format. Example data uses safe synthetic test values.</p><div className="mt-4 flex gap-3"><button className="action" onClick={()=>setFormat('json')}>JSON</button><button className="action" onClick={()=>setFormat('csv')}>CSV</button></div><label className="mt-4 block text-sm text-slate-200">Or upload a JSON or CSV file<input className="mt-1 block text-sm" type="file" accept=".json,.csv" onChange={upload}/></label></section>;
 const isJson=format==='json';
 return <section className="card"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-lg font-semibold">Import Threat Intelligence</h3><p className="text-sm text-slate-200">Input format: <strong>{format.toUpperCase()}</strong> · Example data is safe and synthetic.</p></div><button className="action" onClick={()=>setFormat(null)}>Change format</button></div><div className="mt-3 rounded-lg border border-cyber-600 bg-cyber-900/70 p-3 text-sm text-slate-100"><strong>{isJson?'JSON':'CSV'} schema</strong><p className="mt-1">Required: <code>indicator_type</code>, <code>value</code>. Optional: <code>source</code>, <code>description</code>, <code>tags</code>, <code>confidence</code> (0–1), <code>severity</code>, <code>expires_at</code>, <code>enabled</code>.</p><p className="mt-1">Types: IPV4, IPV6, DOMAIN, URL. {isJson?'Use an array of indicator objects.':'First row must be the column headers.'}</p></div><textarea className="control mt-3 h-52 font-mono" value={content} onChange={e=>setContent(e.target.value)} placeholder={isJson?'Paste a JSON array, or click Use Example.':'Paste CSV with a header row, or click Use Example.'}/><div className="mt-3 flex flex-wrap gap-2"><button className="action" onClick={()=>{setContent(examples[format]);setError('')}}>Use Example</button><button className="action" onClick={()=>setContent('')}>Clear</button><button className="action" onClick={submit}>Import {format.toUpperCase()}</button><label className="action cursor-pointer">Upload file<input className="hidden" type="file" accept={isJson?'.json':'.csv'} onChange={upload}/></label></div>{error&&<p className="ai-status ai-status-failed mt-3">Import error: {error}</p>}{result&&<div className="mt-3 rounded-lg border border-emerald-300/60 bg-emerald-950 p-3 text-sm text-emerald-100"><strong>Import completed</strong><p>Total records: {result.total_records} · New indicators: {result.new_indicators} · Updated: {result.updated_indicators} · Duplicates: {result.duplicates}</p>{result.invalid_records?.length>0&&<ul className="mt-2 list-disc pl-5">{result.invalid_records.map(x=><li key={x.record}>Record {x.record}: {x.error}</li>)}</ul>}</div>}</section>;
}
function Investigation({ item, onRetry }) {
 const error = item.error;
 const title = error?.error_type === 'quota_limit' ? 'Gemini quota limit reached' : error?.error_type === 'provider_unavailable' ? 'AI service temporarily unavailable' : error?.error_type === 'authentication' ? 'Gemini authentication problem' : error?.error_type === 'model_configuration' ? 'Gemini model configuration problem' : error?.error_type === 'timeout' ? 'Gemini request timed out' : 'AI investigation failed';
 const confidenceLabel = item.confidence >= .8 ? 'High' : item.confidence >= .5 ? 'Moderate' : 'Low';
 return <div className="mt-5 border-t border-cyber-600 pt-4 text-sm space-y-4">
  {item.status === 'FAILED' ? <div className="ai-result-block"><p className="ai-status ai-status-failed">⚠ {title}</p><p className="mt-2 leading-6 text-slate-200">{error?.message || 'The investigation could not be completed. Local monitoring remains active.'}</p>{error?.retryable && onRetry && <button className="action mt-3" onClick={onRetry}>Retry Investigation</button>}</div> : <div className="ai-result-grid"><div className="ai-result-block"><p className="ai-section-title">Assessment</p><span className={`assessment-badge assessment-${item.assessment || 'UNKNOWN'}`}>{item.assessment === 'BENIGN' ? '✓' : item.assessment === 'SUSPICIOUS' ? '⚠' : item.assessment === 'MALICIOUS' ? '⚠' : '?'} {item.assessment || item.status}</span></div>{item.confidence != null && <div className="ai-result-block"><p className="ai-section-title">AI Confidence</p><p className="text-lg font-bold text-slate-100">{confidenceLabel} <span className="text-sm font-medium text-slate-300">{Math.round(item.confidence * 100)}%</span></p></div>}</div>}
  {item.summary && <div className="ai-result-block"><h4 className="ai-section-title">Investigation Summary</h4><p className="leading-6 text-slate-100">{item.summary}</p></div>}
  {item.evidence?.length > 0 && <div className="ai-result-block"><h4 className="ai-section-title">Evidence</h4>{item.evidence.map((e, i) => <div className="mb-2 rounded border border-cyber-600 p-2 text-slate-100" key={i}><p>• {e.description || String(e)}</p>{e.evidence_type && <p className="mt-1 text-xs font-semibold uppercase tracking-wide text-cyan-200">Evidence type: {e.evidence_type}</p>}</div>)}</div>}
  {item.sources?.length > 0 && <div className="ai-result-block"><h4 className="ai-section-title">Supporting Sources</h4><div className="grid gap-2 sm:grid-cols-2">{item.sources.filter(s=>{try { const u=new URL(typeof s==='string'?s:s.source_url); return ['http:','https:'].includes(u.protocol) } catch { return false }}).map((s, i) => { const url=typeof s==='string'?s:s.source_url; const host=new URL(url).hostname; return <a key={i} className="rounded-md border border-cyan-300/50 bg-cyber-900 p-3 text-cyan-100 hover:bg-cyber-700 focus:outline-none focus:ring-2 focus:ring-cyan-200" target="_blank" rel="noreferrer" href={url}><span className="block text-xs font-bold uppercase text-cyan-200">Source</span><span className="block break-all underline underline-offset-2">{host}</span></a>})}</div></div>}
  {item.limitations?.length > 0 && <div className="ai-result-block"><h4 className="ai-section-title">Limitations</h4>{item.limitations.map((x, i) => <p className="mb-1 leading-6 text-slate-200" key={i}>• {x}</p>)}</div>}
  {item.status === 'COMPLETED' && <p className="text-xs font-medium text-slate-300">Confidence reflects the available evidence, not whether this indicator is harmless. Web grounding: Not used.</p>}
  <p className="text-xs font-medium text-slate-300">Model: {item.model || '-'} · Investigated: {new Date(item.created_at).toLocaleString()}</p>
 </div>;
}
