"""FastAPI application entry point.

Wires together the API, database, packet sniffer, and detection engine.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.alerts import router as alerts_router
from app.api.routes import router as system_router
from app.api.incidents import router as incidents_router
from app.api.security import router as security_router
from app.api.threat_intelligence import router as threat_intelligence_router
from app.capture.sniffer import PacketMetadata, PacketSniffer
from app.config import API_HOST, API_PORT
from app.database.database import SessionLocal, init_db
from app.detection.engine import DetectionEngine
from app.services.alert_service import AlertService
from app.services.security_controls import SecurityControls
from app.services.threat_intelligence import ThreatIntelligenceService

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


# Shared state
_detection_engine: DetectionEngine | None = None
_sniffer: PacketSniffer | None = None


def _replace_capture(interface: str | None = None) -> PacketSniffer:
    """Safely replace the capture thread after an analyst changes adapter."""
    global _sniffer
    if _sniffer is not None:
        _sniffer.stop()
    _sniffer = PacketSniffer(callback=_on_packet, interface=interface)
    _sniffer.start()
    return _sniffer


def _alert_callback(alert_data: dict) -> None:
    """Persist an alert generated by the detection engine."""
    db = SessionLocal()
    try:
        svc = AlertService(db)
        svc.create_alert(
            alert_type=alert_data["alert_type"],
            severity=alert_data["severity"],
            description=alert_data["description"],
            source_ip=alert_data.get("source_ip"),
            destination_ip=alert_data.get("destination_ip"),
            source_port=alert_data.get("source_port"),
            destination_port=alert_data.get("destination_port"),
            protocol=alert_data.get("protocol"),
            metadata=alert_data.get("metadata"),
        )
    except Exception:
        logger.exception("Failed to persist alert")
    finally:
        db.close()


def _traffic_stat_callback(stats: dict) -> None:
    """Persist periodic traffic statistics."""
    db = SessionLocal()
    try:
        svc = AlertService(db)
        svc.record_traffic_stat(
            packets_per_second=stats.get("current_pps", 0),
            bytes_per_second=stats.get("current_bps", 0),
            unique_sources=stats.get("unique_sources", 0),
            unique_destinations=stats.get("unique_destinations", 0),
        )
    except Exception:
        logger.exception("Failed to record traffic stat")
    finally:
        db.close()


def _on_packet(meta: PacketMetadata) -> None:
    if _detection_engine:
        _detection_engine.process_packet(meta)


def _threat_matches(packet: dict) -> list[dict]:
    """Database work happens after capture metadata extraction, never in Scapy."""
    db = SessionLocal()
    try:
        service = ThreatIntelligenceService(db)
        results = []
        for indicator, field in service.match(packet):
            match = service.record(indicator, field, packet)
            results.append({
                "alert_type": "THREAT_INTELLIGENCE", "severity": indicator.severity,
                "description": f"Threat-intelligence match: {field} matched {indicator.indicator_type} indicator from {indicator.source}.",
                "source_ip": packet.get("source_ip"), "destination_ip": packet.get("destination_ip"),
                "protocol": packet.get("protocol"),
                "metadata": {"indicator_id": indicator.id, "indicator_value": indicator.value, "indicator_type": indicator.indicator_type, "matched_field": field, "confidence": indicator.confidence, "source": indicator.source, "tags": indicator.tags, "match_id": match.id},
            })
        return results
    finally:
        db.close()


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _detection_engine, _sniffer

    logger.info("Initializing database...")
    init_db()

    logger.info("Starting detection engine...")
    _detection_engine = DetectionEngine(
        alert_callback=_alert_callback,
        traffic_stat_callback=_traffic_stat_callback,
        threat_matcher=_threat_matches,
    )
    # Apply persisted analyst rule settings to these live detector instances.
    db = SessionLocal()
    try:
        for rule in SecurityControls(db).rules():
            _detection_engine.apply_rule(rule.rule_type, bool(rule.enabled), __import__("json").loads(rule.settings))
    finally:
        db.close()
    app.state.detection_engine = _detection_engine
    app.state.replace_capture = _replace_capture

    logger.info("Starting packet capture...")
    try:
        db = SessionLocal()
        config = SecurityControls(db).capture_configuration()
        db.close()
        _replace_capture(config.interface_name if config.mode == "MANUAL" else "")
    except Exception:
        logger.exception("Failed to start packet capture – continuing without live capture")

    logger.info("Application started  API=%s:%s", API_HOST, API_PORT)
    try:
        yield
    finally:
        if _sniffer:
            _sniffer.stop()
        logger.info("Application stopped")


app = FastAPI(
    title="Network Anomaly Detection System",
    version="1.0.0",
    description="Lightweight network monitoring and anomaly detection MVP",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(system_router)
app.include_router(alerts_router)
app.include_router(incidents_router)
app.include_router(security_router)
app.include_router(threat_intelligence_router)


@app.get("/api/capture/status")
def capture_status():
    if _sniffer is None:
        return {"running": False, "packet_count": 0}
    return {
        "running": _sniffer.is_running,
        "state": _sniffer.state,
        "packet_count": _sniffer.packet_count,
        "interface": _sniffer.interface,
        "requested_interface": _sniffer.requested_interface or None,
        "auto_selected": _sniffer.auto_selected,
        "configuration_warning": _sniffer.configuration_warning,
        "last_error": _sniffer.last_error,
    }


def main() -> None:
    import uvicorn

    uvicorn.run(
        "app.main:app",
        host=API_HOST,
        port=API_PORT,
        reload=False,
        log_level="info",
    )


if __name__ == "__main__":
    main()
