import pptxgen from 'file:///C:/Users/hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pptxgenjs/dist/pptxgen.es.js';

const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'Network Anomaly Detector team';
pptx.subject = 'Lightweight Network Anomaly Detection System';
pptx.title = 'Network Anomaly Detection System';
pptx.company = 'Student Project';
pptx.lang = 'en-US';
pptx.theme = { headFontFace: 'Aptos Display', bodyFontFace: 'Aptos', lang: 'en-US' };
pptx.defineLayout({ name:'CUSTOM_WIDE', width:13.333, height:7.5 });
pptx.layout='CUSTOM_WIDE';

const C={bg:'07111F', panel:'101D30', panel2:'142842', text:'F2F7FC', muted:'B7C6D8', cyan:'41D9F4', blue:'5B8CFF', green:'5EE5A8', amber:'FFC857', red:'FF6B7A', line:'294766'};
const root = process.cwd();
const screenshot=`${root}/tmp/pdfs/manual-01.png`;
function box(s,x,y,w,h,fill=C.panel,line=C.line,r=0.14){s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:r,fill:{color:fill},line:{color:line,transparency:10}})}
function text(s,t,x,y,w,h,opts={}){s.addText(t,{x,y,w,h,fontFace:'Aptos',fontSize:opts.size||18,color:opts.color||C.text,bold:opts.bold||false,margin:opts.margin??0,breakLine: false,fit:'shrink',valign:opts.valign||'mid',bullet:opts.bullet,align:opts.align||'left',paraSpaceAfterPt:opts.para||0});}
function title(s,t,sub=''){text(s,t,.65,.38,12,.45,{size:25,bold:true}); if(sub) text(s,sub,.67,.9,11.8,.28,{size:10,color:C.cyan,bold:true}); s.addShape(pptx.ShapeType.line,{x:.65,y:1.25,w:12.0,h:0,line:{color:C.line,width:1}})}
function footer(s,n){text(s,'NETWORK ANOMALY DETECTION SYSTEM',.65,7.15,4.5,.16,{size:7,color:C.muted});text(s,String(n).padStart(2,'0'),12.15,7.12,.5,.18,{size:8,color:C.cyan,align:'right'});}
function note(s,t){try{s.addNotes(t)}catch{}}
function addSlide(t,sub,notes){const s=pptx.addSlide();s.background={color:C.bg}; title(s,t,sub); note(s,notes); return s;}
function card(s,heading,body,x,y,w,h,accent=C.cyan){box(s,x,y,w,h);s.addShape(pptx.ShapeType.rect,{x,y,w:.07,h,fill:{color:accent},line:{color:accent}});text(s,heading,x+.24,y+.18,w-.45,.25,{size:14,bold:true});text(s,body,x+.24,y+.52,w-.45,h-.65,{size:10,color:C.muted,valign:'top'});}
function flow(s,items,y=3.1){const w=1.75,g=.22,start=.63;items.forEach((item,i)=>{const x=start+i*(w+g);box(s,x,y,w,.8,i===items.length-1?C.blue:C.panel2);text(s,item,x+.08,y+.15,w-.16,.5,{size:13,bold:true,align:'center'});if(i<items.length-1)s.addShape(pptx.ShapeType.chevron,{x:x+w+.03,y:y+.25,w:.16,h:.3,fill:{color:C.cyan},line:{color:C.cyan}});});}

let s=addSlide('Network Anomaly Detection System','PROJECT PRESENTATION | FUNCTIONAL MVP / PROTOTYPE','Introduce a lightweight, rule-based monitoring and investigation platform. Avoid claiming enterprise-grade coverage or market traction.');
text(s,'Lightweight security monitoring for understanding suspicious network activity',.78,1.6,6.3,1.1,{size:27,bold:true});text(s,'Collect network metadata, apply explainable detection rules, connect alerts into incidents, and provide analyst context.',.8,2.95,5.7,.7,{size:15,color:C.muted});box(s,7.45,1.35,4.9,4.55,C.panel2);text(s,'DETECT',7.9,1.9,3.9,.45,{size:26,bold:true,color:C.cyan,align:'center'});text(s,'UNDERSTAND',7.9,3.0,3.9,.45,{size:26,bold:true,color:C.green,align:'center'});text(s,'INVESTIGATE',7.9,4.1,3.9,.45,{size:26,bold:true,color:C.amber,align:'center'});footer(s,1);

s=addSlide('Why network visibility matters','THE PROBLEM');flow(s,['Network activity','Many events','Hard to interpret','Security risk'],2.35);card(s,'Operational challenge','Smaller teams need visibility without a large dedicated SOC. Raw network events alone do not explain priority or context.',.75,4.05,5.7,1.5,C.amber);card(s,'Project focus','Turn packet metadata into explainable alerts, incidents, risk context, and investigation support.',6.9,4.05,5.7,1.5,C.cyan);footer(s,2);

s=addSlide('Target customer segments','PRODUCT TARGETING | PROPOSED');[['Small and medium organizations','Need practical monitoring with a smaller operational footprint.'],['Educational institutions','Often operate diverse networks with limited security staffing.'],['Small IT and security teams','Need clearer alert context and investigation support.'],['Local deployment users','May value customization and local operational support.']].forEach((v,i)=>card(s,v[0],v[1],.75+(i%2)*6.05,1.7+Math.floor(i/2)*2.15,5.55,1.65,[C.cyan,C.green,C.amber,C.blue][i]));footer(s,3);

s=addSlide('Our solution','ILLUSTRATIVE WORKFLOW');flow(s,['Collect','Detect','Enrich','Correlate','Investigate','Understand'],2.25);text(s,'The platform captures network metadata, applies transparent rules, matches local threat indicators, creates alerts and incidents, then gives the analyst AI-assisted context.',.9,4.0,11.3,.8,{size:17,color:C.muted,align:'center'});footer(s,4);

s=addSlide('How the system works','IMPLEMENTED ARCHITECTURE');const steps=['Network traffic','Packet collector','Metadata extraction','Detection + TI','Alerts','Correlation','Incidents','Risk','AI investigation','Dashboard'];steps.forEach((v,i)=>{const col=i<5?0:1;const row=i%5;const x=col?.0+7.0:.9;const y=1.55+row*1.0;box(s,x,y,5.25,.66,row===4&&col===1?C.blue:C.panel);text(s,v,x+.2,y+.16,4.8,.25,{size:14,bold:true});if(!(col===1&&row===4))s.addShape(pptx.ShapeType.downArrow,{x:x+2.48,y:y+.7,w:.25,h:.18,fill:{color:C.cyan},line:{color:C.cyan}})});footer(s,5);

s=addSlide('Technical architecture','VERIFIED TECHNOLOGY STACK');[['Packet capture','Python + Scapy'],['Backend API','FastAPI + Pydantic'],['Persistence','SQLAlchemy + SQLite'],['Frontend','React + Vite + Tailwind CSS'],['Visualization','Recharts + Lucide'],['Container option','Docker Compose'],['AI enrichment','Gemini REST API, optional']].forEach((v,i)=>card(s,v[0],v[1],.8+(i%3)*4.1,1.55+Math.floor(i/3)*1.6,3.7,1.18,[C.cyan,C.green,C.blue,C.amber,C.cyan,C.green,C.blue][i]));footer(s,6);

s=addSlide('Detection engine','EXPLAINABLE RULE-BASED DETECTION');flow(s,['Network metadata','Detection rules','Security alert'],5.25);[['Port scan','Unique destination ports in a sliding window','HIGH'],['Connection burst','High connection count per source','MEDIUM'],['Traffic spike','Rate exceeds rolling baseline','MEDIUM'],['DNS anomaly','Query bursts or long domain names','MEDIUM'],['Suspicious outbound','Configured destinations or untrusted traffic','HIGH / LOW']].forEach((v,i)=>card(s,v[0],`${v[1]}\nAlert severity: ${v[2]}`,.72+(i%3)*4.18,1.5+Math.floor(i/3)*1.65,3.82,1.3,[C.cyan,C.green,C.amber,C.blue,C.red][i]));footer(s,7);

s=addSlide('Threat intelligence','OFFLINE INDICATOR MANAGEMENT AND MATCHING');flow(s,['Indicator','Normalize','Active check','Match','Evidence','Alert','Incident','Risk'],2.1);text(s,'Supported indicators: IPv4, IPv6, domain, and URL. Indicators retain source, confidence, severity, expiration, enabled state, import support, and historical match evidence.',.85,4.15,11.5,.65,{size:15,color:C.muted,align:'center'});text(s,'A match provides context. It does not prove malicious activity by itself.',2.1,5.25,9,.35,{size:15,color:C.amber,bold:true,align:'center'});footer(s,8);

s=addSlide('AI-assisted investigation','ANALYST ENRICHMENT LAYER');flow(s,['Indicator','Request','Gemini','Assessment','Evidence','Analyst context'],2.25);card(s,'What it returns','Assessment, confidence in available evidence, evidence type, validated sources, and limitations.',.85,4.05,5.45,1.4,C.cyan);card(s,'Control boundary','AI enriches evidence. It does not replace deterministic detection or automatically change security decisions.',6.95,4.05,5.45,1.4,C.amber);text(s,'English | አማርኛ',5.05,5.9,3.2,.3,{size:16,bold:true,color:C.green,align:'center'});footer(s,9);

s=addSlide('Alert, incident, and risk context','FROM EVENTS TO EXPLAINABLE PRIORITY');flow(s,['Event','Alert','Correlation','Incident','Risk contributors','Explainable risk'],2.25);text(s,'The system connects related security evidence into incidents rather than leaving the analyst with isolated events.',1.0,4.2,11.2,.6,{size:18,color:C.muted,align:'center'});footer(s,10);

s=addSlide('Operator documentation','EXCERPT FROM PROJECT MANUAL');box(s,.75,1.45,7.25,4.95,C.panel);s.addImage({path:screenshot,x:.95,y:1.65,w:6.85,h:4.55,sizing:{type:'contain',x:.95,y:1.65,w:6.85,h:4.55}});card(s,'Operator views','The frontend provides dashboard, rules and controls, incidents, devices, threat intelligence, imports, and AI investigations.',8.45,1.65,3.9,1.55,C.cyan);card(s,'Documentation evidence','This excerpt comes from the project manual. A live application screenshot was not available as a repository asset.',8.45,3.55,3.9,1.3,C.green);footer(s,11);

s=addSlide('Controlled laboratory environment','SAFE TESTING ONLY');flow(s,['Kali Linux VM','Controlled test traffic','Detector host','Security dashboard'],2.35);text(s,'The lab guide recommends an isolated host-only or internal virtual network in the 192.168.56.0/24 range. Do not run attack simulations against networks you do not own or control.',1.05,4.3,11.1,.65,{size:16,color:C.muted,align:'center'});footer(s,12);

s=addSlide('Validation and testing','REPOSITORY TESTS AND CONTROLLED SCENARIOS');flow(s,['Generate controlled event','Collector sees metadata','Rule matches','Alert','Incident','Dashboard'],2.15);[['Port scan','Expected PORT_SCAN alert'],['Connection burst','Expected connection anomaly'],['Traffic spike','Expected traffic anomaly'],['DNS burst / long name','Expected DNS anomaly'],['TI matching','Evidence, alert, correlation, incident']].forEach((v,i)=>card(s,v[0],v[1],.85+(i%3)*4.05,4.05+Math.floor(i/3)*1.15,3.7,.85,[C.cyan,C.green,C.amber,C.blue,C.red][i]));footer(s,13);

s=addSlide('Product positioning','A PRACTICAL SECURITY OPERATIONS WORKFLOW');[['Lightweight','Designed for a smaller operational footprint.'],['Integrated','Combines detection, TI, incidents, and investigation.'],['Explainable','Connects risk to stored contributors and evidence.'],['AI-assisted','Adds analyst context without changing detection decisions.'],['Localizable','Supports English and አማርኛ AI explanations.'],['Ethiopia-first potential','A target context, not a market claim.']].forEach((v,i)=>card(s,v[0],v[1],.78+(i%3)*4.14,1.55+Math.floor(i/3)*2.1,3.75,1.55,[C.cyan,C.green,C.amber,C.blue,C.cyan,C.green][i]));footer(s,14);

s=addSlide('Ecosystem context','CAPABILITY POSITIONING, NOT A RANKING');const rows=[['Network anomaly detection','✓','✓','—','✓'],['Threat intelligence','Varies','✓','✓','✓'],['Incident correlation','Varies','✓','Limited','✓'],['AI investigation','Varies','Varies','Varies','✓'],['Lightweight workflow','Varies','Varies','Varies','Target']];const x=[.8,5.0,7.1,9.1,11.1];['Capability','IDS','SIEM/XDR','TI platform','This project'].forEach((v,i)=>text(s,v,x[i],1.5,i?1.5:4.0,.3,{size:12,bold:true,color:C.cyan,align:i?'center':'left'}));rows.forEach((r,ri)=>{box(s,.75,1.9+ri*.75,11.9,.58,ri%2?C.panel:C.panel2);r.forEach((v,ci)=>text(s,v,x[ci],2.05+ri*.75,ci?1.5:4,.2,{size:11,color:ci===4?C.green:C.text,align:ci?'center':'left'}));});footer(s,15);

s=addSlide('Proposed business model','NOT CURRENT REVENUE');[['Target customers','SMEs, educational institutions, and teams with limited security staffing.'],['Value proposition','Understand suspicious network activity without a large dedicated SOC.'],['Deployment and setup','Installation, configuration, network integration, and initial tuning.'],['Managed monitoring','Alert review, incident assistance, and periodic reports.'],['Support subscription','Maintenance, updates, and configuration assistance.'],['Customization and optional AI/TI','Organization-specific rules, dashboards, and enrichment capacity.']].forEach((v,i)=>card(s,v[0],v[1],.75+(i%2)*6.05,1.5+Math.floor(i/2)*1.58,5.55,1.22,[C.cyan,C.green,C.amber,C.blue,C.cyan,C.green][i]));footer(s,16);

s=addSlide('Why customers may pay','THE SERVICE OPPORTUNITY');flow(s,['Existing tools','Operational challenge','Local service','Clearer security operations'],2.25);text(s,'Customers may pay for deployment, configuration, integration, alert interpretation, investigation, monitoring, and support. The value comes from the operational service around technology.',1.05,4.15,11.2,.75,{size:18,color:C.muted,align:'center'});footer(s,17);

s=addSlide('Limitations and current stage','CANDID MVP ASSESSMENT');[['Rule-based detection','Rules remain explainable but do not equal a mature enterprise IDS.'],['AI assessment','Analysts must verify AI-generated context and sources.'],['Threat intelligence','Quality depends on locally configured indicator sources.'],['Validation scope','Controlled lab results do not establish large-scale production performance.'],['Operational hardening','Authentication, scaling, integration, and tuning remain future work.']].forEach((v,i)=>card(s,v[0],v[1],.8+(i%3)*4.1,1.55+Math.floor(i/3)*1.7,3.72,1.35,[C.red,C.amber,C.blue,C.cyan,C.green][i]));text(s,'Current stage: Functional MVP / Prototype',3.65,5.6,6,.35,{size:18,bold:true,color:C.amber,align:'center'});footer(s,18);

s=addSlide('Roadmap and conclusion','NEXT STEPS');[['Current','Functional MVP with rule-based detection, TI, incidents, dashboard, and AI investigation.'],['Next','Additional TI integrations, stronger detection coverage, and production hardening.'],['Later','Organization-specific intelligence and managed security services.']].forEach((v,i)=>card(s,v[0],v[1],.9+i*4.15,1.7,3.75,1.75,[C.cyan,C.green,C.blue][i]));text(s,'Detect. Understand. Investigate. Respond.',1.45,4.75,10.5,.65,{size:30,bold:true,color:C.cyan,align:'center'});text(s,'Questions?',5.35,5.7,2.6,.35,{size:20,color:C.text,align:'center'});footer(s,19);

await pptx.writeFile({ fileName: `${root}/Network_Anomaly_Detector_Presentation.pptx` });
